HigherOrderCO/HVM

src/compiler.rs
This fixes these warnings while compiling on Linux:
```
main.hovm.out.c:110:8: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
Stk  free[MAX_ARITY];
^
main.hovm.out.c:129:8: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
Worker workers[MAX_WORKERS];
^
main.hovm.out.c:1160:5: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
u64 normal_seen_data[normal_seen_mcap];
^
main.hovm.out.c:1334:23: warning: incompatible pointer to integer conversion assigning to 'Thd' (aka 'unsigned long') from 'void *' [-Wint-conversion]
workers[t].thread = NULL;
```
=> fix C compilation warnings on Linux

src/compiler.rs
I introduced some mistakes in the compiler with my last commit when I replaced some extraneous uses of the `format!` macro. Sorry about that. I think this fixes those though, but please do check.
=> Fix compiler mistakes.

Cargo.nix, NIX.md, bench/README.md
Since Cargo.lock was changed with commit 6975488b0c253ee598981aaaf3260d7d9cfab74c. (Note: when Cargo.lock changes, `crate2nix generate` needs to be ran to update Cargo.nix)
=> Improve Nix usage instructions. Regenerate Cargo.nix.

Cargo.lock, Cargo.toml, src/compiler.rs, src/rulebook.rs, src/runtime.c
This allows the use of regular `{` and `}` tokens in the C file instead of the escaping required for every scope and control flow structure. It should be a QOL improvement while developing the C file, compared to the cost of a few string allocations while compiling to C ?
Also a couple of drive-by changes: 
- removes some, I believe unused, cranelift crates: hvm will be faster to build
- some automated rustfmt, and println simplifications
(I haven't fully tested this, only on one example, which seemed to work. Hopefully CI will soon be able to test this PR)
=> compiler: switch to token replacement instead of format strings

HOW.md
I propose two changes in the Readme because these are subtly unexpected expressions that may be significant but go unexplained. So it is either a typo, or something more advanced that is not explained.
`({λx(x) λy(x)} 10)` -> `({λx(x) λy(y)} 10)` (There does not seem to be any use of the shared variable `x`, and variables cannot be shared anyway).`
The other one seems wrong, as the notation `{a b} = c` has never been introduced. Even if at this point it may make sense to replace `dup a b = c` by `{a b} = c`, a note about it would be welcome.
```
({a b} c)
----------------------- App-Sup
{x0 x1} = c --> dup x0 x1
{(a x0) (b x1)}
```
=> Two small changes in 'supperposed application'

Cargo.lock, Cargo.nix, Cargo.toml, src/parser.rs
Ok so the major changes in this PR so far are:
* I removed some functions that seemed unused/unneeded:
* `equal_at`, whose usages I replaced with `rest`.
* `flatten`, which is just the `concat` method for slices.
* `lines`, which was kinda bad anyway, as it unnecessarily allocated memory.
* `head_default`, no longer needed due to changes to `skip_spaces`.
* `skip` no longer recurses, which should prevent that function from causing any stack overflows. It also mutates its argument now (not sure if that's bad, doesn't seem like it affects anything though).
* Similarly, the function signatures of `skip_comment` and `skip_spaces` now explicitly state that the argument is mutated (it seems like they were previously implicitly mutating their arguments anyway?).
* The `rest` method now doesn't …
=> Improve and add tests for parser.

Cargo.lock, Cargo.toml, src/main.rs
This PR adds `clap` to the codebase, a `cli parser`.
It includes:
- Help messages
- Short and long names: so you can choose to use `hvm r <file>` or `hvm run <file>`
I did tests using the example folder and the README one.
=> fix #100 - cli parsing with clap.

bench/LambdaArithmetic/main.hs
The HVM implementation uses B0. This was probably a typo
=> Fix mistake in LambdaArithmetic/main.hs

Cargo.lock, flake.lock
Fixes `nix build` by updating `Cargo.lock` and `flake.lock`
=> Updating Cargo.lock and flake.lock for successful nix build

README.md
As of gcc, `-pthread` defines some macros additionally that are crucial under some use cases, while `-lpthread` only tells the linker to link the pthread library. [Clang docs](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-pthread) also explicitly mentioned the `-pthread` argument.
Note that there are issues complaining about clang only uses `-pthread` during compile time but not link time which triggers an unused argument warning (see https://github.com/mesonbuild/meson/issues/2628), but on my machine with clang 14.0.6 I can't reproduce the warning.
See also: https://stackoverflow.com/a/23251828/8553479
=> docs: always use -pthread instead of -lpthread

Cargo.lock, Cargo.toml, src/api.rs, src/builder.rs, src/cli.rs, src/compiler.rs, src/language.rs, src/lib.rs, src/main.rs, src/parser.rs, src/readback.rs, src/rulebook.rs, src/runtime.rs
HVM only uses OS services for some things, including opening files and for the CLI program. Thus, a restricted subset of the HVM library can technically run without them. So I added a `std` feature, enabled by default, that compiles HVM to use the standard library. When it's disabled using `default-features = false` by a library that uses it, HVM will compile in `#![no_std]` mode, which prevents using the `std` library but allows running in embedded and kernel environments. 
I had to change some things to allow this. First of all, `regex` requires std, so the compiler to C is disabled in `no_std` mode. `std::collections::HashMap` was replaced by `hashbrown::HashMap` because std's requires the OS RNG. All imports from STD were changed with imports from `core` or `alloc`. Future commits …
=> Add no-std support.

src/compiler.rs, src/main.rs, src/runtime.c
Previously, generated code allocated a hard-coded 8GiB heap, causing issues like https://github.com/Kindelia/HVM/issues/140 and https://github.com/Kindelia/HVM/issues/35.
This PR makes the heap size depend upon the compile-time flag `-M` (already used by `hvm r`).
As a side effect, this changes the default heap size for compiled programs to 4GiB (the default value of `-M` flag).
=> Compiler: respect -M flag

.github/workflows/nix.yml, NIX.md, default.nix, flake.lock, flake.nix, rust-toolchain.toml, shell.nix
This replaces `crate2nix` with `nix-cargo-integration` to make the "flake.nix" file more manageable.
Should fix #161.
=> Simplify flake.nix

src/runtime/base/precomp.rs
Fixed arity of both constructors that are types and not numbers. In the kind2 type checker the `Kind.Term.num` is the term that stores a U60 number so we will probably have to create a `Kind.Term.float` or something similar.
=> Fixed U60 and F60 precomp arity

src/runtime/base/reducer.rs
Previously this code did not run in version 1.0.5-beta.
(Fib 0 x0 x1) = x0
(Fib i x0 x1) = (Fib (- i 1) x1 (+ x0 x1))
(Main n) = (Fib 500000 0 1)
and this one in version greater than 1.0.5-beta.
(Head (Cons x xs)) = (Some x)
(Head Nil) = None
(UnwrapOr (Some x) y) = x
(UnwrapOr None y) = y
(SumFirstTwo Nil) = 0 
(SumFirstTwo (Cons x xs)) = (+ x (UnwrapOr (Head xs) 0))
(Iter f x 0) = x
(Iter f x n) = (f (Iter f x (- n 1)))
(Fib n) = (Head (Iter λxs (Cons (SumFirstTwo xs) xs) (Cons 0 (Cons 1 Nil)) n))
(Main n) = (Fib 10000)
Now with these changes both programs are working perfectly, without loss of performance...
=> fix reduce

flake.nix, src/compiler/mod.rs
This adds rust-toolchain.toml to HVM compilation outputs so cargo should be able to compile them successfully, which should fix #185 . I also changed flake.nix to use nix-filter so it only includes the files that are actually used in the derivation, to make them smaller.
=> Address #185

src/main.rs
I'm not a Rust dev but this did the trick 😁 
This helped me chain commands in Bash scripts, eg. `hvm run -f "${MAIN_HVM}" && echo "Finished"` etc.
=> Add exit(1) if a command failed

README.md
With the new command the nightly version is not installed as default, as it was done before
=> Change command to install rust nightly

src/runtime/mod.rs
Runtime creation was either panicking or getting killed by the system because it was creating as many threads as the heap size, instead of reading the thread count variable.
=> fix: fix `Runtime::new` and `Runtime::from_code_with`.

src/runtime/mod.rs
`System::new_all` does a lot more than just measuring available mem, so let's cut those extra syscalls to make startup faster.
Bench (examples/hello):
Old:
```
$ hyperfine "target/release/main run '(Main 0)'"
Benchmark 1: target/release/main run '(Main 0)'
Time (mean ± σ):     513.4 ms ±  36.6 ms    [User: 285.6 ms, System: 455.2 ms]
Range (min … max):   469.5 ms … 587.2 ms    10 runs
```
New:
```
$ hyperfine "target/release/main run '(Main 0)'"
Benchmark 1: target/release/main run '(Main 0)'
Time (mean ± σ):      77.5 ms ±   4.9 ms    [User: 18.0 ms, System: 59.9 ms]
Range (min … max):    67.2 ms …  85.6 ms    33 runs
```
=> Speed up default_heap_size

src/language/readback.rs
Previously, superpositions of strings were not rendering as strings. This causes issues when you try to open a file or print a string that happens to be superpositioned.
This fixes it so that superpositioned strings are rendered correctly as strings.
I learned a little bit about HVM, and the fix was surprisingly easy!
I'm not sure if my understanding that the first value of a SUP pointer will always point to the value that is to be cloned is correct, or of the second value could potentially be the value to be cloned, and the first value might be a variable pointer.
If I got it wrong, then we'll need to check both the first and the second value to see if either one is a string.
=> fix: correctly render superposed strings.

Cargo.lock, Cargo.toml, src/runtime/mod.rs
You can now compile HVM as a library with only 24 dependencies!
- Feature gate the `clap` dependency, which is not needed when using HVM as a library.
- Move `sysinfo` to an optional, but default, feature so that users can chose to exclude it if they are manually providing the heap size.
- Remove the unused highlight_error crate.
=> feat: reduce required dependencies.

examples/hello/main.hvm
This helps prevent users from running into the confusing message: "Inconsistent arity on: '(Main *)'" because they didn't pass an argument to `hvm run -f hello/main.hvm`.
=> fix: remove unused argument from hello world example.

src/language/syntax.rs, src/runtime/base/debug.rs, src/runtime/base/precomp.rs
To reflect recent changes in https://github.com/HigherOrderCO/Kindex , this is needed for Kind to run properly.
Maybe we could think of something else, since it's in a way making HVM depend on Kind.
=> Update precompiled function names after Kindex reorganization

guide/README.md
This pull request addresses the need to update the GitHub repository URL in the README.md guide. The current URL is outdated, and this change reflects the correct repository URL.
- Updated the GitHub repository URL in the README.md guide.
The existing repository URL in the README.md file is pointing to an outdated location, causing confusion for users who try to install HVM. This update ensures that users are directed to the correct repository URL, improving the overall user experience.
=> docs: Update GitHub repository URL in the README.md guide

src/hvm.rs
Keeps consistency between implementations
=> Change `vars` to type `&'a mut [APort]` in reference implementation

src/hvm.c
```
cargo:warning=src/hvm.c:113:25: warning: integer overflow in expression of type ‘int’ results in ‘-2147483648’ [-Woverflow]
cargo:warning=  113 | #define G_RBAG_LEN (TPC * RLEN)
cargo:warning=      |                         ^
cargo:warning=src/hvm.c:118:18: note: in expansion of macro ‘G_RBAG_LEN’
cargo:warning=  118 |   APair rbag_buf[G_RBAG_LEN]; // global rbag buffer
cargo:warning=      |                  ^~~~~~~~~~
cargo:warning=src/hvm.c:118:9: error: size of array ‘rbag_buf’ is negative
cargo:warning=  118 |   APair rbag_buf[G_RBAG_LEN]; // global rbag buffer
cargo:warning=      |         ^~~~~~~~
cargo:warning=In file included from src/hvm.c:4:
cargo:warning=src/hvm.c: In function ‘push_redex’:
cargo:warning=src/hvm.c:113:25: warning: integer overflow in expression of type …
```
=> fix overflow when compiling on machines with >64 cores

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs
This PR exposes the inner modules so that other projects can use HVM as a library. More focus on designing stabler APIs would be interesting in the future.
=> Expose modules as a library

src/hvm.c, src/hvm.cu
This commit fixes the issue of expressions like `+0 - +3` returning the wrong result
=> Match `i24` implementation from C and CUDA to Rust

src/main.rs
Hi!
This pull request introduces a new command-line argument -V to the HVM Rust project. The purpose of this argument is to print the current version of the application using the value specified in the Cargo package.
Changes:
Added a new CLI argument -V.
Implemented functionality to fetch and display the version from the Cargo package.
Details:
Modified src/main.rs to include the -V argument.
Utilized the env! macro to retrieve the version from Cargo.toml.
Updated the help message to include the new -V option.
Usage:
Running hvm -V will now print the current version of the application.
Motivation:
Adding the -V argument enhances the user experience by providing an easy way to check the application version directly from the command line. This aligns with common CLI conventions and improves …
=> HVM cli arg version

src/ast.rs
The parser expects no spaces between "&" and "!".
=> Fix printing of "!" in redexes

Cargo.lock, Cargo.toml, src/ast.rs, src/main.rs, tests/programs/safety-check.hvm, tests/run.rs, tests/snapshots/run__file@empty.hvm.snap, tests/snapshots/run__file@safety-check.hvm.snap
Related to #362.
This PR kind of fixes the issue, but not really. While this new version does return an error in the previously thought "correct" version of the program, which is expected since it actually performed unsafe operations, it doesn't error in the second version, which does the same. Returning an error in this version is much harder, since it's not cloning an unsafe definition, but an unsafe expression. According to Nicolas, that could be solved with an affine type system.
=> Propagate unsafety to definitions that depend on unsafe definitions

.github/workflows/bench.yml, examples/demo_io/main.bend, examples/demo_io/main.hvm, src/run.c, src/run.cu, tests/programs/io/read_and_print.hvm, tests/snapshots/run__io_file@demo_io__main.hvm.snap, tests/snapshots/run__io_file@io__read_and_print.hvm.snap
- Adds a `SEEK` io operation.
- replace `READ_LINE` and `READ_CHAR` with just a `READ`, taking in the number of bytes to be read.
- `READ` and `WRITE` now operate on lists of bytes
=> add io_seek, operate on bytes instead of strings

src/cmp.rs, src/hvm.c, src/hvm.cu, src/hvm.cuh, src/hvm.h, src/run.c, src/run.cu
Defining `bool` ourselves can cause all sorts of problems. For example, if the implementation of the libraries we're using import another another definition of bool, HVM will not compile.
Or if a user tries to write FFI for HVM and includes a definition of bool.
One option was to `#define bool _Bool`, which is what stdbool does, but including the standard library is the more standard way of doing it.
Also, `hvm.cuh` tried to redefine `bool` in c++ which would cause an error.
Another effect is that we can now compile hvm with C23
=> Use bool type from stdbool.h
