HigherOrderCO/HVM

- .github/workflows/clippy.yml
- .github/workflows/rustfmt.yml
- rustfmt.toml
- src/lambolt.rs
- src/main.rs
- src/parser.rs
- src/runtime.rs
- src/text.rs
Formats rust code and runs clippy linting on pushes and pull requests.
> Add GitHub actions

- README.md
- src/builder.rs
- src/compiler.rs
- src/language.rs
- src/main.rs
- src/rulebook.rs
This just adds the `-lpthread` flag to the C compilation step.
> Fix compilation instruction.

- HOW.md
- README.md
- flake.nix
Added `crate2nix` to dev shell as so that `crate2nix generate` can be ran when Cargo.lock changes.
> Improve HOW.md. Add `crate2nix` to dev shell.

- prep.sh
- src/lib.rs
> could we write a pre-publish script or something like that? i will never remember to run that command in particular  :P
_Originally posted by @quleuber in https://github.com/Kindelia/HVM/issues/30#issuecomment-1024412887_
> Add prep script.

- HOW.md
This change fixes what looks like a mismatch in terms between a reduction step and its written explanation.
> Correct tB to yB

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.nix
- HOW.md
- prep.sh
- src/language.rs
- src/lib.rs
- src/parser.rs
- src/runtime.rs
Addresses:
> Also, it would be great if we could test in multiple platforms/compilers on CI. @nothingnesses any ideas?
_Originally posted by @quleuber in https://github.com/Kindelia/HVM/issues/62#issuecomment-1029216699_
> Improve CI and fix stuff.

- Cargo.lock
- src/builder.rs
- src/compiler.rs
- src/language.rs
- src/lib.rs
- src/main.rs
- src/parser.rs
- src/readback.rs
- src/rulebook.rs
- src/runtime.rs
* formatting
* fixing clippy warnings
* small fixes on some comments
> fix CI errors

- README.md
Changed the Telegram Group Link
> Fixed Telegram Link

- src/rulebook.rs
This PR should be merged to the new type checker work. Please only merge it and create a release when the new Kind2 type checker is merged on the master.
> Fix HOAS for the new type checker

- Cargo.lock
- Cargo.toml
- src/runtime.rs
Maybe we should do something like
```rust
...
pub const RESERVED_QUANTITY: u64 = 4;
pub const FIRST_IO: u64 = RESERVED_QUANTITY + 1;
...
pub const IO_QUANTITY: u64 = 4;
pub const HOAS_CT0 : u64 = RESERVED_QUANTITY + IO_QUANTITY + 1;
...
```
?
> fix reserved ids

- src/rulebook.rs
- src/runtime.rs
Doesn't handle read/write errors yet
> Add IO.load and IO.store to access files

- tests/quick_sort/quick_sort.hvm
Fixes #142
The test now calculates the expected answer, and quickly.
> Do arithmetic mod-2^32 in `quick_sort` test

- src/rulebook.rs
> Fix flatten for rules with num, add test

- guide/README.md
Avoids some possible pitfalls for new users.
> Update Installation Instructions

- examples/sort/bubble/main.hs
- examples/sort/bubble/main.hvm
This gives me a ~3x speedup or so.
> Speed up bubble sort benchmark with extra bangs

- guide/README.md
Change commandline flag syntax.
> `-c` -> `-c true` in guide/READM.md

- src/runtime/base/memory.rs
- src/runtime/base/program.rs
> Update AtomicU64::as_mut_ptr() usages to as_ptr()

- Cargo.toml
- LICENSE
Changes:
* add LICENSE file with Apache 2.0
* changes license on Cargo.toml
* bumps version of Cargo.toml
> Add Apache 2.0 licensing

- paper/PAPER.typst
> docs: update PAPER.typst

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
Solves https://github.com/HigherOrderCO/HVM/issues/352
> remove rust-toolchain.toml and update Cargo.toml

- src/ast.rs
- tests/run.rs
- tests/snapshots/run__file@empty.hvm.snap
> error gracefully when `@main` is missing
